version: '3.1'

services:
  db:
    container_name: weather_db_pawelu
    image: postgres:12.4
    restart: always
    environment:
      POSTGRES_DB: weatherDB
      POSTGRES_USER: root
      POSTGRES_PASSWORD: pass123
    ports:
      - 7432:5432